Task/12 film description
0ldCold/film_library pull request #22
Opened 2024-03-15 16:35 UTC by Red-Fox-98

2024-03-15 18:22 UTC, 0ldCold commented
Название ПРа нормальное?
Ссылка на таску в описании?

![image](https://github.com/0ldCold/film_library/assets/34031600/9942050c-e085-4299-b935-46baf55e6308)

2024-03-15 19:12 UTC, 0ldCold requested changes

2024-03-15 20:50 UTC, Red-Fox-98 commented on packages/frontend/yarn.lock
> Чето слишком много изменений в лок файле
в данном файле что конкретно надо подправить?

2024-03-15 20:59 UTC, Red-Fox-98 commented on packages/frontend/src/widgets/film/DescriptionModule/types.ts
> +export type Contributor = "Автор" | "Источник"
> Это должен быть enum. Т.е. это должно быть английское слово, обозначающее тип. Лейбл может меняться, enum не изменится никогда enum хранится в БД

сам тип поменять или имя переменной?

2024-03-15 21:01 UTC, Red-Fox-98 commented on packages/frontend/src/pagesFsd/film/Film.tsx
> +    StudioLogoMock
> Зачем менялся порядок?

я иногда нажимала по привычке ctrl+alt+L, может быть так сортировка сработала

2024-03-15 21:02 UTC, Red-Fox-98 commented on packages/frontend/src/widgets/film/DescriptionModule/Contributor.tsx
> +        src={type == "Автор" ? avatar ?? Avatar404.src : ""}
> Не надо так делать. Если type != "Автор", то надо НЕ рендерить компонент

может тогда type != "Источник"?

2024-03-15 21:16 UTC, Red-Fox-98 commented on packages/frontend/src/widgets/film/DescriptionModule/LanguageButton.tsx
> +    <div className={Styles.language_button} onClick={() => onClick?.(language)}>
> Чето странная логика. Как мне кажется - мы при нажатии должны передавать новый язык, а не текущий. Т.е. логика "ротации" языка должна быть инкапсулирована в этот компонент

я подправила, но в тот компонент передается новый язык, что не так?

2024-03-15 21:21 UTC, Red-Fox-98 commented on packages/frontend/src/widgets/film/DescriptionModule/types.ts
> +  };
> Можно создать отдельный тип и сделать вот так:
> 
> ```ts
> export type FilmDescription = Record<FilmDescriptionLanguage, FilmDescriptionData>;
> ```

так лучше сделать или ты это привел в пример и это не обязательно?

2024-03-16 08:53 UTC, 0ldCold commented on packages/frontend/yarn.lock
Я откатил изменения в yarn.lock, package.json и потом заново сделал `yarn add html-react-parser markdown-it`, `yarn add -D @types/markdown-it`

2024-03-16 08:53 UTC, 0ldCold commented on packages/frontend/yarn.lock
Потому, что ВОЗМОЖНО ты что-то не так сделала

2024-03-16 09:08 UTC, 0ldCold commented on packages/frontend/src/widgets/film/DescriptionModule/types.ts
> +}
Ну я не совсем это имел ввиду. Ты потом в Contributor в качестве лейбла используешь значение строки. 

Нельзя привязываться к строкам, если только это не явное "имя" или какое-то свойство, которое ничем не ограничено. Т.е. Имя пользователя может быть любым. А вот роль - ограничена каким-то списком существующих в приложении ролей.

```ts
export type ContributorType = "author" | "externalSource";
```

И потом исходя из типа ты отображаешь в лейбле тот или иной текст

2024-03-16 09:08 UTC, 0ldCold commented on packages/frontend/src/widgets/film/DescriptionModule/DescriptionModule.tsx
> +  const text = parse(markdownit().render(data[language].text));
Нет. "Результат функции `markdownit()` можно вынести из компонента"

1. Это результат всего парса маркдауна, а не результат функции `markdownit()`
2. Это ты вынесла не "из компонента", а "из рендера компонента"

Функция `markdownit()`, скорей всего, генерирует парсер по конфигам. Конфиг у тебя не меняется. Поэтому эту генерацию парсера можно вынести из компонента.

Т.е. `const mdParser = markdownit()` написать на 14 строке. 

А `parce(....)` верни обратно в тело рендера. Ну или оберни в `useMemo`

2024-03-16 09:08 UTC, 0ldCold commented on packages/frontend/src/pagesFsd/film/Film.tsx
> +    StudioLogoMock
Просто это мешает код ревью

2024-03-16 09:16 UTC, 0ldCold commented on packages/frontend/src/widgets/film/ContributorModule/Contributor.tsx
> +  };
Это делается проще:

`{data.type !== "Автор" && (<Image ... />}`
Пихай прямо на прежнее место.

Т.е. если условие выполняется, то будет возвращаться `<Image />`. Иначе `false`. `false` не будет отображаться. Так происходит из-за особенности работы условных операторов в JS. Я тебе про это рассказывал

2024-03-16 09:16 UTC, 0ldCold commented on packages/frontend/src/widgets/film/DescriptionModule/LanguageButton.tsx
> +    <div className={Styles.language_button} onClick={() => onClick?.(language)}>
В компонент передается старый язык сейчас. И передавался старый. 

Т.е. в компонент передается "ru". Мы отображаем в компоненте следующий язык (en). А при нажатии на кнопку мы должны возвращать новый язык: "en".

Т.е. у компонента есть текущий язык (ru) и есть функция, которая возвращает НОВОЕ значение языка. 
Как выбирается новое значение, что отображается в самом компоненте (т.е. новое значение языка сейчас) - это исключительно забота компонента и это должно быть в нем инкапсулировано.

Т.е. если у нас появится 3-й язык, то мы должны поправить ТОЛЬКО компонент LanguageButton

2024-03-16 09:21 UTC, 0ldCold requested changes

2024-03-16 09:21 UTC, 0ldCold commented on packages/frontend/src/widgets/film/LanguageButton/LanguageButton.tsx
> +export type Language = "ru" | "en";
Нам этот тип теперь не нужен. У нас есть тип `FilmDescriptionLanguage`

2024-03-16 09:21 UTC, 0ldCold commented on packages/frontend/src/widgets/film/DescriptionModule/Contributor.tsx
> +const Contributor: FC<ContributorProps> = ({ type, name, avatar }) => {
Этот компонент можно перенести в слой entities или features. 

entities - это не интерактивные (с точки зрения пользователя) компоненты или компоненты, взаимодействие с которыми не несет бизнес смысла

features - это интерактивные компоненты

интерактивные - это те, с которыми можно взаимодействовать. Т.е., грубо говоря, можно нажать и что-то произойдет

В данном случае это, скорей всего, features

2024-03-16 09:21 UTC, 0ldCold commented on packages/frontend/src/widgets/film/DescriptionModule/LanguageButton.tsx
> +const LanguageButton: FC<LanguageButtonProps> = ({ language, onClick }) => {
Этот компонент можно перенести в слой features.

2024-03-18 11:31 UTC, Red-Fox-98 commented on packages/frontend/src/widgets/film/ContributorModule/Contributor.tsx
> +  };
> Это делается проще:
> 
> `{data.type !== "Автор" && (<Image ... />}` Пихай прямо на прежнее место.
> 
> Т.е. если условие выполняется, то будет возвращаться `<Image />`. Иначе `false`. `false` не будет отображаться. Так происходит из-за особенности работы условных операторов в JS. Я тебе про это рассказывал

`{data.type !== "Источник" && (<Image ... />}` 
тогда лучше так, true будет возвращаться если type будет не равен "Источник"

2024-03-18 12:23 UTC, Red-Fox-98 commented on packages/frontend/src/widgets/film/DescriptionModule/types.ts
> +}
> Ну я не совсем это имел ввиду. Ты потом в Contributor в качестве лейбла используешь значение строки.
> 
> Нельзя привязываться к строкам, если только это не явное "имя" или какое-то свойство, которое ничем не ограничено. Т.е. Имя пользователя может быть любым. А вот роль - ограничена каким-то списком существующих в приложении ролей.
> 
> ```ts
> export type ContributorType = "author" | "externalSource";
> ```
> 
> И потом исходя из типа ты отображаешь в лейбле тот или иной текст

```
export type EnumContributor = "Автор" | "Источник";
```
получается так лучше прописать?

2024-03-18 17:37 UTC, 0ldCold commented on packages/frontend/src/widgets/film/DescriptionModule/types.ts
> +}
По английски.
Понимаешь?

Основная претензия в том, что у тебя в типах прописываешь текст, который ты потом используешь в качестве лейбла.

Так делать нельзя. Потому, что этот текст может поменяться. Надо создавать "псевдоним" на по-английски. Который будет храниться в БД потом на бэке. И потом псевдоним превращаешь в лейбл. 

У тебя же в БД не будет храниться, например, роли "Пользователь" или "Администратор".  У тебя будет храниться user, admin и т.д. 

Также у тебя может появиться локализация в приложении. И надо будет переводить на другие языки. 

Короче сделай как сделано в статусах. Вот тут (скрин ниже). Я этот модуль делал.

![image](https://github.com/0ldCold/film_library/assets/34031600/7daa6e2e-2bf4-47e8-83b3-37955dbb0754)

2024-03-19 14:59 UTC, 0ldCold requested changes

2024-03-19 14:59 UTC, 0ldCold commented on packages/frontend/src/features/film/LanguageButton/LanguageButton.tsx
> +  onClick?: (type: FilmDescriptionLanguage) => void;
type -> newLanguage

2024-03-19 15:16 UTC, Red-Fox-98 commented on packages/frontend/src/features/film/Contributor/Contributor.tsx
> +      <div className={Styles.name}>{parse(markdownit().render(`[${data.name}]()`))}</div>
> эмм
> 
> А тут зачем нужен парс маркдауна? У нас же в маркдауне приходит только текст
> 
> Тут просто {data.name}, нет? Или ты не знаешь как сделать ссылку?
> 
> Ссылка - это тег .

так при клике на имя переходит на страницу пользователя

2024-03-19 15:55 UTC, 0ldCold approved these changes

2024-03-19 18:51 UTC, merged