Добавлен блок на страницу фильма У друзей
0ldCold/film_library pull request #23
Opened 2024-03-27 14:48 UTC by Red-Fox-98

#11

2024-03-27 15:41 UTC, 0ldCold requested changes

2024-03-27 15:41 UTC, 0ldCold commented on packages/frontend/src/widgets/film/FriendsFilm/types.ts
> +  episodesTotal: number | null;
Не верные типы.
У пользователя есть конкретные списки аниме/фильмов. Все списки можешь посмотреть в меню добавления в список.
![image](https://github.com/0ldCold/film_library/assets/34031600/07441cb5-495a-4e7d-85a7-031c3d063383)
В списках "брошено", "пересматриваю", "смотрю" и т.д. может находиться аниме с указанным числом просмотренных серий.

Т.е. в данном случае будет приходить enum с названием списка, в котором находится данное аниме у друга.
Его можно взять из типа `UserFilmsListType`. Перенеси этот тип в shared/api для того, чтобы можно было его везде переиспользовать.
Также число рядом с названием списка - это не номер серии, а оценка. Которая может быть опциональной.
Т.е. реальный тип будет выглядеть вот так:
```ts
export interface IFilmFriends {
  friend: {
    name: string;
    avatar?: string;
  };
  list: UserFilmsListType;
  rate?: number;
}
```

2024-03-27 15:41 UTC, 0ldCold commented on packages/frontend/src/features/film/Friend/Friend.module.scss
> +  height: 23px;
А зачем указывать высоту?

2024-03-27 15:41 UTC, 0ldCold commented on packages/frontend/src/features/film/Friend/Friend.module.scss
> +  padding-left: 2px;
Отступы между элементами внутри flex лучше делать при помощи gap у flex контейнера

2024-03-27 15:41 UTC, 0ldCold commented on packages/frontend/src/features/film/Friend/Friend.module.scss
> +  align-content: center;
Это точно работает? Это правило вроде как должно быть определено для flex контейнера, а не для элемента внутри него.

2024-03-27 15:41 UTC, 0ldCold commented on packages/frontend/src/widgets/film/FriendsFilm/FriendsFilm.module.scss
> +  margin: -13px 0 15px 0;
Давай уберем эти отступы. Я знаю, что это не как в оригинале, но в оригинале там вообще отступы от шапки до контента модуля от балды везде лепят (в разных местах разные)

2024-03-27 15:41 UTC, 0ldCold commented on packages/frontend/src/widgets/film/FriendsFilm/FriendsFilm.module.scss
> +}
Тут не хватает align-items: center. У тебя разная высота у "друга" и теста справа от него. Поэтому надо их выровнять по центру.

![image](https://github.com/0ldCold/film_library/assets/34031600/47279536-d344-48da-8c21-bd1b26428d0a)

2024-03-27 15:41 UTC, 0ldCold commented on packages/frontend/src/widgets/film/FriendsFilm/FriendsFilm.module.scss
> +  align-content: center;
Это точно ли тут нужно?

Мне кажется, что ты не jочень хорошо разбираешься в основных 4 инструментах по работе с flex:
1. `justify-content` - отвечает за позиционирование "по горизонтали"
2. `align-items` - позиционирование "по вертикали"
3. `gap` - расстояние между элементами
4. `flex-direction` - возможность превратить строку в столбик. Тогда justify-content и alignItems "инвертируются", так сказать

И вот все эти стили нужно пихать в flex КОНТЕЙНЕР. Т.е. туда, где находится display: flex, в который складываются элементы строки.

2024-03-27 15:41 UTC, 0ldCold commented on packages/frontend/src/pagesFsd/film/Film.module.scss
> +  width: 25%;
Я понимаю, что в оригинале используются проценты, но лучше зафиксировать ширину колонки "menu" в пикселях. В Оригинале ширина этой колонки не сильно меняется (минимум 204, максимум 240). Но эта процентная ширина (если она не 100%) не всегда работает "очевидно".

Я бы сделал для menu ширину, допустим, 240px, а content будет занимать все оставшееся пространство. Т.е. его ширина будет 100%

2024-03-27 15:41 UTC, 0ldCold commented on packages/frontend/src/features/film/Friend/Friend.tsx
> +          alt={friend.avatar ?? ""}
Ты не совсем понимаешь для чего нужен атрибут alt у изображения (у тега <img>)

Этот тег нужен для 2 вещей:
1. Этот текст отобразится, если изображение по какой-то причине не загрузится
2. Этот текст отображается в "скринридерах", Т.е. в инструментах для слабовидящих. Эти инструменты "читают" сайт и озвучивают его для слабовидящего (или слепого) пользователя.

Т.е. тебе нужно описать, что изображено на картинке. В данном случае мы можем сюда просто написать текст "аватарка пользователя". Т.к. конкретное изображение на аватарке не несет смысловой нагрузки, и пользователь будет это знать. Т.е. будет `alt={"аватарка пользователя"}`.

Если бы мы писали какую-то статью для блога и вставляли бы какое-то важное изображения (например график цен на нефть), то мы бы писали в alt что-то типо "График цен на нефть за 2000-2024 года на международном рынке".

2024-03-27 15:41 UTC, 0ldCold commented on packages/frontend/src/widgets/film/FriendsFilm/types.ts
> +  episodesTotal: number | null;
Тут не совсем твоя ошибка.
Тут скорее проблема в постановке задания. Надо было мне описать смысл модуля текстом.

2024-03-27 17:14 UTC, 0ldCold commented
А еще смерджи сюда main, чтобы подтянуть пайплайны

2024-03-28 15:05 UTC, 0ldCold commented on packages/frontend/src/features/film/Friend/Friend.module.scss
> +  height: 23px;
А зачем она вообще нужна?
Что она ограничивает?

2024-03-28 15:06 UTC, Red-Fox-98 commented on packages/frontend/src/features/film/Friend/Friend.module.scss
> +  align-content: center;
> Это точно работает? Это правило вроде как должно быть определено для flex контейнера, а не для элемента внутри него.

это для того чтоб аватарка пользователя была примерно по вертикали посередине, и чтоб было еще примерно на ровне с никнеймом

2024-03-28 16:46 UTC, 0ldCold requested changes

2024-03-29 10:52 UTC, 0ldCold requested changes

2024-03-29 10:52 UTC, 0ldCold commented on packages/frontend/src/widgets/film/FriendsFilm/FriendsFilm.tsx
> +              {viewingStatus(friendsFilm.list, Number(friendsFilm.rate))}
Тут все еще есть проблема
Ты написала функцию, у которой `rate` имеет тип `number`
И пытаешься в него запихнуть `friendsFilm.rate`, который имеет тип `number | undefiend`
Но TS не позволяет

Далее ты превращаешь это в `number` при помощи `Number()`
А потом в самой функции проверяешь через обходные пути, "а существует ли rate"


Тебе не кажется, что в твоей логике закралась ошибка?

2024-03-29 10:52 UTC, 0ldCold commented on packages/frontend/src/widgets/film/FriendsFilm/FriendsFilm.module.scss
> +  display: grid;
а грид зачем?

2024-03-29 10:52 UTC, 0ldCold commented on packages/frontend/src/features/film/Friend/Friend.module.scss
> +  height: 23px;
Я все еще не понимаю, зачем тут height.
Мы вроде уже выяснили, что он ничего не ограничивает. Он только создает "отступ" между строчками. И отступ нужно создавать при помощи других инструментов.

2024-03-29 11:34 UTC, 0ldCold approved these changes

2024-03-29 11:40 UTC, merged