Страница фильма
0ldCold/film_library pull request #3
Opened 2023-11-19 11:54 UTC by Aeronnax

2023-12-18 11:47 UTC, 0ldCold requested changes

2023-12-18 11:47 UTC, 0ldCold commented on packages/frontend/src/entities/ContentInformation/ContentInformation.module.scss
> +.templateStyle {
Просмотрел нейминг в других компонентах.

У тебя небольшое недопонимание нейминга классов:
у тебя имя класса должно быть уникальным ВНУТРИ КОМПОНЕНТА, а не внутри всей страницы. То-есть тебе не надо добавлять приписки в виде названия компонента всем классам. Достаточно объяснить, какую роль играет блок/блоки, к которому привязан класс внутри данного компонента.

Небольшое пояснение про "роль": смысл в том, чтобы НЕ создавать классы вида `blueBackground`, `row`, а создать класс `wrapper`, в котором у тебя будет синий фон и позиционирование в одну строчку (т.е. контент класса `row`)

2023-12-18 11:47 UTC, 0ldCold commented on packages/frontend/src/entities/WrapperBlockWidget/BlockInfoRight/RatingAggregator/RatingAggregator.tsx
> +const RatingAggregator: FC<RatingAggregatorProps> = ({ children }) => {
В данном случае бесполезный компонент. Надо сделать как в `StudioBlock`:
1. Добавить сюда заголовок модуля 
2. Вывести тут же отображение рейтинга

Уточнение по пункту 2:
В ДАННОМ случае у тебя очень простое отображение. Т.е. в виде текста и цифры, а не в виде кучи звездочек. И эту логику можно уместить тут.
В последствии ты сделаешь отдельный компонент со звездочками, в который ты будешь тупо передавать рейтинг в виде одного числа (например `5`, `5.5`, `10`), а компонент будет сам уже отрисовывать звезды. И заменишь реализацию в виде текста на компонент.

2023-12-18 11:47 UTC, 0ldCold commented on packages/frontend/src/entities/WrapperBlockWidget/BlockInfoRight/RatingAggregator/Scores/Rating/Container/Container.tsx
> +const Container: FC<ContainerProps> = ({ children }) => {
Бесполезно, перенести в `RatingAggregator`

2023-12-18 11:47 UTC, 0ldCold commented on packages/frontend/src/entities/WrapperBlockWidget/BlockInfoRight/RatingAggregator/Scores/Rating/Rating.tsx
> +const Rating: FC<RatingProps> = ({ children }) => {
Бесполезно, перенести в `RatingAggregator`

2023-12-18 11:47 UTC, 0ldCold commented on packages/frontend/src/entities/WrapperBlockWidget/BlockInfoRight/RatingAggregator/Scores/Rating/TextСontainer/Praise/Praise.tsx
> +const Praise: FC<PraiseProps> = ({ children }) => {
Бесполезно, перенести в `RatingAggregator`

2023-12-18 11:47 UTC, 0ldCold commented on packages/frontend/src/entities/WrapperBlockWidget/BlockInfoRight/RatingAggregator/Scores/Rating/TextСontainer/TextСontainer.tsx
> +const TextСontainer: FC<TextСontainerProps> = ({ children }) => {
Бесполезно, перенести в `RatingAggregator`

2023-12-18 11:47 UTC, 0ldCold commented on packages/frontend/src/entities/WrapperBlockWidget/BlockInfoRight/RatingAggregator/Scores/Scores.tsx
> +const Scores: FC<ScoresProps> = ({ children }) => {
Бесполезно, перенести в `RatingAggregator`

2023-12-18 11:47 UTC, 0ldCold commented on packages/frontend/src/entities/WrapperBlockWidget/WrapperBlockWidget.tsx
> +const WrapperBlockWidget: FC<WrapperBlockWidgetProps> = ({ children }) => {
1. Виджеты (судя по названию) должны состоять в отдельной папке `widgets`
2. В данном случае это бесполезный компонент. Перенести логику в виджет карточки

2023-12-18 11:47 UTC, 0ldCold commented on packages/frontend/src/features/FillingInInformation/FillingInInformation.tsx
> +const FillingInInformation: FC<FillingInInformationProps> = ({ label, children }) => {
1. Это не `feature`
2. Посмотри на обсуждение компонента `LineContainer`

2023-12-18 11:47 UTC, 0ldCold commented on packages/frontend/src/features/FillingInInformation/ValueFillingInInformation/ValueFillingInInformation.tsx
> +const ValueFillingInInformation: FC<ValueFillingInInformationProps> = ({ value }) => {
1. Это не `feature`
2. Посмотри на обсуждение компонента `LineContainer`

2023-12-18 11:47 UTC, 0ldCold commented on packages/frontend/src/features/UserСomments/UserСomments.tsx
> +const UserСomments: FC = () => {
Я бы назвал это "FilmActions`. Тут же будут не только комменты

2023-12-18 11:47 UTC, 0ldCold commented on packages/frontend/src/widgets/template/MainTemplate/MainTemplate.tsx
> +const MainTemplate: FC<MainTemplateProps> = ({ children }) => {
Ты не совсем понял концепцию `template`. Шаблон - это какая-то основа сайта, которая универсальная для разных страниц этого сайта. В твоем же случае это не так. 

Тебе нужно вернуть тут все как было (а именно чтобы тут был только фон, `SectionWrap`, который можно будет сделать прямо тут (то-есть удалить компонент и классы перенести сюда) и `children`, которые ты запихнешь в этот `SectionWrap`. 
Кстати тег для `SectionWrap` будет `<main>`

2023-12-18 11:47 UTC, 0ldCold commented on packages/frontend/src/widgets/template/MainTemplate/MainTemplate.tsx
> +          <Subtitle titleOfTheWork='Наименование Фильма'>
Дальше вот это вот все ты будешь описывать в `src/pageFsd/film/Film.tsx`. Где ты будешь использовать MainTemplate, и внутри которого будет заталкивать заголовок, хлебные крошки и прочее.

2023-12-18 11:47 UTC, 0ldCold commented on packages/frontend/src/widgets/template/MainTemplate/MainTemplate.tsx
> +            <div className={Styles.contentWidget}>
Хлебные крошки лучше сделать в виде отдельного компонента, в который ты будешь передавать массив `value={[Аниме, Сериалы, 2023 года]}`. И там он уже будет сам генерировать нужно кол-во компонентов (через `{value.map(item => <Breadcrumds ...  />)}` )

2023-12-18 11:47 UTC, 0ldCold commented on packages/frontend/src/widgets/template/MainTemplate/MainTemplate.tsx
> +          <PageContent>
Вот это вот все ты должен вынести в виджет `FilmCard` (`src/widgets/film/FilmCard`), о котором упоминалось выше. 

Или, кстати, просто на странице, `Film` оставить (`src/pagesFsd/film/Film`). Но надо понимать, что там у тебя будет тупо использовать куча модулей и верстка, позиционирующая их. То-есть у тебя не будет куча вложенностей одного компонента в другой. Это будет в коде конкретного модуля. 
Вот пример модуля:
![image](https://github.com/0ldCold/film_library/assets/34031600/10b29f18-433a-4d53-9b39-46b72a4e484f)

То-есть все, что изображено на этой картинке - это один конкретный модуль. И выглядеть от у тебя будет примерно как `<Info data={film.info} />`. Бег вложенностей. `film` - это объект со всеми данными по фильму, получаемый с бэка. (потом. сейчас ты просто создашь такой объект и заполнишь его поля самостоятельно).

И суть данного компонента (речь про `Film`) - получить с бэка данные и расфасовать их по модулям. Ну и спозиционировать модули относительно друг друга.

2023-12-18 11:47 UTC, 0ldCold commented on packages/frontend/src/widgets/template/MainTemplate/MainTemplate.tsx
> +          <PageContent>
Модули - это будут, скорей всего, виджеты (`src/widgets/film/...`)

2023-12-18 11:47 UTC, 0ldCold commented on packages/frontend/src/widgets/template/Subtitle/Subtitle.tsx
> +    <header>
Это не `header`. `header` зачастую только один на странице и это - шапка сайта. Это просто обычный div. 
То, что ты понимаешь под `header`, а именно заголовок основного контента страницы, хранится в теге `h1`.

2023-12-18 11:47 UTC, 0ldCold commented on packages/frontend/src/widgets/template/Subtitle/Subtitle.tsx
> +        {children}
сюда не желательно пихать что-то, кроме текста. Поэтому можешь убрать `flex` и `flex-direction: column-reverse`. 

Вообще хлебные крошки не являются частью заголовка (а именно об этом информирует название компонента) и их нужно запихнуть в просто в `Film`

Итого в сухом остатке у тебя на странице остаются только `h1`, который можно вынести в `Film`

2023-12-19 14:43 UTC, Aeronnax commented on packages/frontend/src/entities/ContentInformation/ContentInformation.module.scss
> +  padding-right: 10px;
Не совсем понял вопрос "Зачем?" За веру и народ! 
Пытался стилизовать полоску, из-за неопытности сделал не правильно, как я понял. На твой вопрос "Почему не спросил?". Переделывание собственной работы оставляет шикарный отпечаток в памяти и лучше сделать один раз правильно, чем переделывать 100/500 раз. Но для начала нужно переделать.  Так как идет сверху вниз, это ты увидишь первым. Сегодня я до 12  и спать. Недосып в 25 дает о себе знать

2023-12-19 14:43 UTC, Aeronnax commented on packages/frontend/src/entities/ContentInformation/ContentInformation.module.scss
> +  width: 264px;
Подправил.

2023-12-19 14:43 UTC, Aeronnax commented on packages/frontend/src/entities/ContentInformation/ContentInformation.module.scss
> +  background: rgb(183, 211, 174);
На сайте в хексах. Я сидел подпирал цвет с помощью кружочка, а он по умолчанию делает в ргб. Сейчас переделал все в хекс. Тут была невнимательность.

2023-12-19 14:43 UTC, Aeronnax commented on packages/frontend/src/entities/MainSection/MainSection.tsx
> +//import Style from "./MainSection.module.scss";
Под него задумывалось запихнуть footer т.е то что находится под сайтом.Так как я копирую сайт, то возможно не совсем понимаю зачем он сделан. Удалять не буду, просто отложу в "Ящик", удалить всегда успею.

2023-12-19 14:43 UTC, Aeronnax commented on packages/frontend/src/entities/PageContent/ContentBlock/BlockAboutContent/BlockAboutContent.module.scss
> +.wrapper {
+- понял то что ты написал. Запрошу пояснение завтра. Что бы подтвердить или опровергнуть  свои догадки.

2023-12-19 14:43 UTC, Aeronnax commented on packages/frontend/src/entities/PageContent/ContentBlock/BlockAboutContent/BlockAboutContent.module.scss
> +  height: 429;
Исправил.

2023-12-19 14:43 UTC, Aeronnax commented on packages/frontend/src/entities/PageContent/ContentBlock/BlockAboutContent/BlockAboutContent.tsx
> +const BlockAboutContent: FC<BlockAboutContentProps> = ({ children }) => {
![image](https://github.com/0ldCold/film_library/assets/74263446/88dd58d7-2d9b-44c6-829c-e218a55d91e4)
Отдельный блок. Который будет для каждого уникальный. Или я не правильно начал его делать?  Т.е сделать виджет в котором полностью блок с информацией. Внутри этого виджета, виджеты по меньше. Т.е деления на левую секцию и правую.

2023-12-19 14:43 UTC, Aeronnax commented on packages/frontend/src/entities/PageContent/ContentBlock/ContentBlock.tsx
> +const ContentBlock: FC<ContentBlockProps> = ({ children }) => {
Проблема копипасты. Некоторые вещи я попросту попытался скопировать. Про Float я почитал, не совсем понял как он работает.

2023-12-19 14:43 UTC, Aeronnax commented on packages/frontend/src/entities/PageContent/PageContent.tsx
> +const PageContent: FC<PageContentProps> = ({ children }) => {
Разделение контента. Если смотреть по шики. То под пейджем будет отдельная логика в ввиде комментариев и прочего. Можно сделать дивом и удалить компонент. Но тут больше затык для меня что бы я сам не забыл для чего он.

2023-12-19 14:43 UTC, Aeronnax commented on packages/frontend/src/entities/SectionWrap/MainSheet/MainSheet.tsx
Хорошо.

2023-12-19 14:43 UTC, Aeronnax commented on packages/frontend/src/entities/SubtitleContent/WrapperPicture/PictureContent/PictureContent.module.scss
> +  background-image: url(./Picture/contentPic.webp);
Переделаю.

2023-12-19 14:43 UTC, Aeronnax commented on packages/frontend/src/entities/WrapperBlockWidget/BlockInfoLeft/BlockInfoLeft.tsx
Попрошу пояснения более подробно.

2023-12-19 14:43 UTC, Aeronnax commented on packages/frontend/src/entities/WrapperBlockWidget/BlockInfoLeft/EntryInfo/EntryInfo.module.scss
Да вижу.

2023-12-19 14:43 UTC, Aeronnax commented on packages/frontend/src/entities/WrapperBlockWidget/BlockInfoLeft/EntryInfo/EntryInfo.tsx
> +const EntryInfo: FC<EntryInfoProps> = ({ children }) => {
Возможно. Сделан был для того что бы разграничить "Информацию"  и все что ниже.

2023-12-19 14:43 UTC, Aeronnax commented on packages/frontend/src/entities/WrapperBlockWidget/BlockInfoLeft/EntryInfo/Line/AdditionalInfo/AdditionalInfo.tsx
> +const AdditionalInfo: FC<AdditionalInfoProps> = ({ children }) => {
Компонент сделан для того что бы отдельно навесить стили на данную строку. Соблюсти отступ, как сделано в шикимори. Возможно у сайта другая задумка, но описать в текстовом варианте сейчас нет сил.

2023-12-19 14:43 UTC, Aeronnax commented on packages/frontend/src/entities/WrapperBlockWidget/BlockInfoLeft/EntryInfo/Line/Line.tsx
> +const Line: FC<LineProps> = ({ children }) => {
Попробую сделать.

2023-12-19 14:43 UTC, Aeronnax commented on packages/frontend/src/entities/WrapperBlockWidget/BlockInfoLeft/EntryInfo/Line/LineContainer/LineContainer.tsx
> +const LineContainer: FC<LineContainerProps> = ({ children }) => {
Попробую сделать.

2023-12-19 14:43 UTC, Aeronnax commented on packages/frontend/src/entities/WrapperBlockWidget/BlockInfoRight/BlockInfoRight.tsx
> +const BlockInfoRight: FC<BlockInfoRightProps> = ({ children }) => {
Разделить левый и правый блок. Как писал выше. Создать виджет карточки, у карточки есть так же два виджита с левым столбиком и правым.

2023-12-19 14:43 UTC, Aeronnax commented on packages/frontend/src/entities/WrapperBlockWidget/BlockInfoRight/BlockStudio/BlockStudio.module.scss
Да.

2023-12-19 14:43 UTC, Aeronnax commented on packages/frontend/src/entities/WrapperBlockWidget/BlockInfoRight/BlockStudio/BlockStudio.tsx
> +const BlockStudio: FC<BlockStudioProps> = ({ children }) => {
Вроде понял.Если что попрошу пояснения.

2023-12-19 14:43 UTC, Aeronnax commented on packages/frontend/src/entities/WrapperBlockWidget/BlockInfoRight/BlockStudio/StudioLogo/StudioLogo.module.scss
> +    margin-right: 42.5px;
Осознал. Исправлю

2023-12-19 14:43 UTC, Aeronnax commented on packages/frontend/src/entities/WrapperBlockWidget/WrapperBlockWidget.tsx
> +const WrapperBlockWidget: FC<WrapperBlockWidgetProps> = ({ children }) => {
Тут проблема с неймингом. Но посыл я понял.

2023-12-19 14:43 UTC, Aeronnax commented on packages/frontend/src/widgets/template/MainTemplate/MainTemplate.tsx
> +const MainTemplate: FC<MainTemplateProps> = ({ children }) => {
Да не понял. Но поздно начал что-то подозревать. Да и вроде был вопрос от меня "Мне сюда все пихать?" 
Ответ был утвердителен. Возможно друг друга не поняли в тот момент.  В любом случае MB

2023-12-19 14:43 UTC, Aeronnax commented on packages/frontend/src/widgets/template/MainTemplate/MainTemplate.tsx
> +            <div className={Styles.contentWidget}>
Надо будет пояснение. Под твоим руководством этим буду заниматься

2023-12-19 14:43 UTC, Aeronnax commented on packages/frontend/src/widgets/template/MainTemplate/MainTemplate.tsx
> +          <PageContent>
Вроде понял. Но не совсем. Хотя выше описал как вижу я. Может в этом посыл?

2023-12-19 14:43 UTC, Aeronnax commented on packages/frontend/src/widgets/template/Subtitle/Subtitle.tsx
> +    <header>
Проблема копипасты сайта. Но смысл уловил

2023-12-19 15:14 UTC, 0ldCold commented on packages/frontend/src/entities/ContentInformation/ContentInformation.module.scss
> +  padding-right: 10px;
При чем тут это все?
Запусти сайт, найди этот компонент в дев-тулзах и "выключи" это свойство. И посмотри что изменится (ничего)

2023-12-19 15:21 UTC, 0ldCold commented on packages/frontend/src/entities/MainSection/MainSection.tsx
> +//import Style from "./MainSection.module.scss";
Для футтера у тебя будет отдельный виджет. Который ты запихнешь в MainTemplate.

У тебя MainTemplate будет выглядеть примерно так:
```html
<div>
  <HeaderComponent />
  <main>
    {children}
  <main>
  <FooterComponent />
</div>
```

2023-12-19 15:32 UTC, 0ldCold commented on packages/frontend/src/entities/PageContent/ContentBlock/ContentBlock.tsx
> +const ContentBlock: FC<ContentBlockProps> = ({ children }) => {
Не копируй сайт вплоть до строчки. Он писался разными людьми в разное время на разных технологиях. Делай то, что ты видишь, периодически обращаясь в его код за размерами/цветами и подобным.

Не знаешь зачем отступ? Если убрать отступ ничего не изменится? Нахуй этот отступ.
Если что-то изменится, но ты видишь во такую херню в виде процентов, то замени на просто какой-то фиксированный отступ (например `10px`)

2023-12-19 15:48 UTC, 0ldCold commented on packages/frontend/src/entities/WrapperBlockWidget/BlockInfoLeft/EntryInfo/EntryInfo.tsx
> +const EntryInfo: FC<EntryInfoProps> = ({ children }) => {
Как я писал где-то в других тредах - не надо прям на столько сильно дробить на отдельные компоненты.

Заголовок карточки "Информация" и факт отображения содержимого карточки относится к самой карточке.

2023-12-19 15:55 UTC, 0ldCold commented on packages/frontend/src/entities/WrapperBlockWidget/BlockInfoLeft/EntryInfo/Line/AdditionalInfo/AdditionalInfo.tsx
> +const AdditionalInfo: FC<AdditionalInfoProps> = ({ children }) => {
Ты весь модуль "Информация" запихиваешь в отдельный виджет. В котором ты можешь сделать конкретную для конкретной строчки создать класс. Не нужно ради одного специфичного класса создавать отдельный компонент.

2023-12-19 15:56 UTC, 0ldCold commented on packages/frontend/src/entities/WrapperBlockWidget/BlockInfoRight/BlockInfoRight.tsx
> +const BlockInfoRight: FC<BlockInfoRightProps> = ({ children }) => {
Ответил в предыдущем комментарии. Удали.

2023-12-19 16:20 UTC, 0ldCold requested changes

2023-12-19 16:20 UTC, 0ldCold commented on packages/frontend/src/entities/ContentInformation/ContentInformation.module.scss
> +  width: 96.5%;
что за магическое число `96.5`?

2023-12-19 16:20 UTC, 0ldCold commented on packages/frontend/src/entities/ContentInformation/ContentInformation.module.scss
> +  width: 96.5%;
Не обязательно везде указывать `max-width: 100%`. Все должно работать без него. Если не работает, то у тебя где-то что-то не так и `max-width: 100%` не выход

2023-12-19 16:20 UTC, 0ldCold commented on packages/frontend/src/widgets/template/MainTemplate/MainTemplate.tsx
> +//import MainSection from "src/entities/MainSection/MainSection";
Почему коммент, а не удаление компонента?

2023-12-19 16:49 UTC, Aeronnax commented on packages/frontend/src/entities/ContentInformation/ContentInformation.module.scss
> +  width: 96.5%;
![image](https://github.com/0ldCold/film_library/assets/74263446/8d461792-4bb3-4b0b-ad50-2aa3943c347d)
Сделал как ты посоветовал. Сейчас убрал вовсе и все ровно работает как надо.

2023-12-19 16:49 UTC, Aeronnax commented on packages/frontend/src/widgets/template/MainTemplate/MainTemplate.tsx
> +//import MainSection from "src/entities/MainSection/MainSection";
![image](https://github.com/0ldCold/film_library/assets/74263446/51105527-3966-48b3-a89e-6c8cde81c031)

2023-12-19 21:17 UTC, 0ldCold commented on packages/frontend/src/widgets/template/MainTemplate/MainTemplate.tsx
> +//import MainSection from "src/entities/MainSection/MainSection";
Ты всегда можешь достать код из истории коммитов PRа. У тебя хранится полная история изменения проекта. Не засирай репозиторий ненужными файлами

2023-12-19 21:21 UTC, 0ldCold commented on packages/frontend/src/entities/ContentInformation/ContentInformation.module.scss
> +  width: 96.5%;
Там было:
```css
width: 264px;
```
Это можно заменить на:
```css
min-width: 264px;
width: 100%;
```
или на:
```css
max-width: 264px;
width: 100%;
```

Смотря что тебе больше подходит по смыслу в данном месте.
1-й вариант сделает так, чтобы блок пытался занять всю ширину контейнера, но имел ширину НЕ МЕНЬШЕ 264px,
2-й вариант делает так, чтобы блок пытался занять всю ширину контейнера, но имел ширину НЕ БОЛЬШЕ 264px

2024-01-13 15:01 UTC, 0ldCold commented on packages/frontend/src/entities/PageContent/ContentBlock/BlockAboutContent/BlockAboutContent.module.scss
> +.wrapper {
Разобрались: Переделали проект под FSD

2024-01-13 15:14 UTC, 0ldCold approved these changes

2024-01-13 15:14 UTC, merged