UI: Фильм. В списках у людей
0ldCold/film_library pull request #47
Opened 2024-05-07 20:07 UTC by Aeronnax

#13

2024-05-08 17:13 UTC, 0ldCold requested changes

2024-05-08 17:13 UTC, 0ldCold commented on packages/frontend/src/entities/film/PeoplesLists/PeoplesLists.tsx
> +const PeoplesLists: FC<PeoplesListsProps> = ({ data }) => {
А зачем копипастить?
Почему бы не переиспользовать BarChart?

2024-05-09 12:28 UTC, Aeronnax commented on packages/frontend/src/entities/film/PeoplesLists/PeoplesLists.tsx
> +const PeoplesLists: FC<PeoplesListsProps> = ({ data }) => {
Понял про что ты говоришь. Нужно сделать проверку и тогда можно будет переиспользовать элемент

2024-05-09 13:25 UTC, 0ldCold requested changes

2024-05-09 13:25 UTC, 0ldCold commented on packages/frontend/src/widgets/film/RateChartModule/RateChartModule.tsx
> +      <BarChart data={transformedData} isFilterLowItems={true} />
Можно просто `<BarChart data={transformedData} isFilterLowItems/>`

2024-05-09 13:25 UTC, 0ldCold commented on packages/frontend/src/widgets/film/PeoplesListsModule/PeoplesListsModule.tsx
> +      <BarChart data={transformedData} isFilterLowItems={false} />
У тебя значения по умолчанию для `isFilterLowItems` не стоит. Т.е. по умолчанию там `undefined`, что приравнивается к `false`

Т.е. можно сделать
`<BarChart data={transformedData} />`

2024-05-09 14:19 UTC, 0ldCold approved these changes

2024-05-09 14:20 UTC, merged