UI: Приложение. Смена темы
0ldCold/film_library pull request #52
Opened 2024-08-14 15:06 UTC by Red-Fox-98

#51

2024-08-15 12:00 UTC, 0ldCold requested changes

2024-08-15 12:01 UTC, 0ldCold commented on packages/frontend/src/entities/film/Author/Author.tsx
> +              <div key={item} className={clsx(Styles.role, theme === 'light' && Styles.lightRole)}>
И этот компонент Typography используешь везде, где у тебя есть текст

2024-08-15 14:20 UTC, Red-Fox-98 commented on packages/frontend/src/shared/store/Theme/slice.ts
> +export const themeSlice = createSlice({
> Тут точно типы никакие не нужны?

тип внутри компонента определяется

2024-08-15 14:22 UTC, Red-Fox-98 commented on packages/frontend/src/entities/film/Author/Author.tsx
> +              <div key={item} className={clsx(Styles.role, theme === 'light' && Styles.lightRole)}>
> У тебя же светлая тема является основной Всмысле по умолчанию
> 
> Тебе нужно было наоборот переопределять цвет если тема темная То-есть верни везде (в других файлах тоже) как было
> 
> Вообще как вариант - можно сделать в shared/uiKit сделать компонент, который будет использовать(в данном месте) примерно вот так:
> 
> ```js
> <Typography className={Styles.role}>{item}</Typography>
> ```
> 
> В нем ты прокидываешь className и children в div какой-нибудь Ну и внутри него в одном месте переопределять цвет для темной темы

не во всех компонентах одинаковые цвета в светлой теме

2024-08-15 15:40 UTC, 0ldCold commented on packages/frontend/src/entities/film/Author/Author.tsx
> +              <div key={item} className={clsx(Styles.role, theme === 'light' && Styles.lightRole)}>
Обсудили в ЛС:
в любом цвет текста в светлой теме ты регулируешь при помощи className
А в темной теме везде белый цвет у текста

2024-09-09 05:23 UTC, 0ldCold requested changes

2024-09-09 05:23 UTC, 0ldCold commented on packages/frontend/src/entities/film/Author/Author.tsx
> +        <Typography className={Styles.name} isWithoutDarkTheme={theme === 'light'}>
Эта логика должна быть инкапсулирована в компонент Typography
Пропс `isWithoutDarkTheme` нужен если для текста вообще никогда не требуется темная тема

2024-09-09 05:23 UTC, 0ldCold commented on packages/frontend/src/entities/film/Author/Author.tsx
> +            <div>{roles.length == 1 ? 'Роль: ' : 'Роли: '}</div>
Зачем врапать в div если мы врапаем в Typography, которые уже внутри себя содержит div?

2024-10-02 14:40 UTC, 0ldCold requested changes

2024-10-02 14:40 UTC, 0ldCold commented on package.json
> +  "packageManager": "yarn@1.22.22+sha512.a6b2f7906b721bba3d67d4aff083df04dad64c399707841b7acf00f6b133b7ac24255f2652fa22ae3534329dc6180534e98d17432037ff6fd140556e2bb3137e"
Это убери
Видимо ты не там вызвала `yarn`

2024-10-02 14:40 UTC, 0ldCold commented on packages/frontend/src/entities/film/ModuleCard/ModuleCard.tsx
> +      <Typography className={clsx(Styles.header, theme === 'dark' && Styles.darkHeader)}>
вот тут, как раз таки, надо использовать `isWithoutDarkTheme={true}`
Т.е. из-за особенности дизайна ты снаружи управляешь подключением темы к тексту, так сказать

2024-10-02 14:40 UTC, 0ldCold commented on packages/frontend/src/entities/film/Related/Related.tsx
> +            <Typography className={clsx(Styles.signs, theme === 'dark' && Styles.darkSigns)}>
Вот тут, наверное, тоже надо добавить `isWithoutDarkTheme={true}`

2024-10-02 14:40 UTC, 0ldCold commented on packages/frontend/src/entities/film/Related/Related.tsx
> +            <Typography className={clsx(Styles.signs, theme === 'dark' && Styles.darkSigns)}>
И тут добавить `isWithoutDarkTheme={true}`

То-есть везде, где ты добавляешь стили в className исходя из текущей темы надо отключать механизм покраски текста в самом компоненте

2024-10-02 14:40 UTC, 0ldCold commented on packages/frontend/src/entities/film/Related/Related.tsx
> +            <Typography className={clsx(Styles.publisher, theme === 'dark' && Styles.darkLabel)}>
и тут

2024-10-02 14:40 UTC, 0ldCold commented on packages/frontend/src/entities/film/Related/Related.tsx
> +            <Typography className={clsx(Styles.story, theme === 'dark' && Styles.darkLabel)}>
и тут

2024-10-02 15:26 UTC, 0ldCold approved these changes

2024-10-02 15:28 UTC, merged